config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :items do
    member do
      patch :complete
    end
  end
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  def completed?
    !completed_at.blank?
  end 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :complete]
  def index
    if signed_in?
      @items = Item.where(:user_id => current_user.id).order("created_at DESC")
    end
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "Item successfully saved!"
      redirect_to root_path
    else
      flash[:danger] = "Error saving Item!"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash[:success] = "Item updated!"
      redirect_to @item
    else
      flash[:danger] = "Error updating item!"
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    flash[:success] = "Item deleted!"
    redirect_to root_path
  end

  def complete
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end


  private

    def item_params
      params.require(:item).permit(:title, :description)
    end

    def find_item
      @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-3">
	<h1>Edit</h1>
	<%= render 'form' %>
</div>

app/views/items/index.html.erb
<% if signed_in? %>
  <div class="col-md-6 col-md-offset-3">
    <% @items.each do |item| %>
    <div class="well">
        <% if item.completed? %>
          <div class="row item">
            <div class="col-md-8">
              <h2 style="opacity: 0.5;">
                <strike><%= link_to item.title, item_path(item) %></strike>
              </h2>
              <p style="opacity: 0.5;"><%= item.description %></p>
              <p style="opacity: 0.5">
                Completed <%= time_ago_in_words(item.completed_at) %>
              </p>
            </div>

            <div class="col-md-2">
              <a href="#"><i class="fa fa-lg fa-check"></i></a>
            </div>

            <div class="col-md-2">
              <%= link_to item_path(item), method: :delete  do %>
                <i class="fa fa-lg fa-trash"></i>
              <% end  %>
            </div>
          </div>
        <% else %>
          <div class="row item">
            <div class="col-md-8">
              <h2><%= link_to item.title, item_path(item) %></h2>
              <p><%= item.description %></p>
              <p>
                Created <%= time_ago_in_words(item.created_at) %>
              </p>
            </div>

            <div class="col-md-2">
              <p><%= link_to complete_item_path(item), method: :patch do %>
                <i class="fa fa-lg fa-check"></i></p>
              <% end %>
            </div>

            <div class="col-md-2">
              <p><%= link_to item_path(item), method: :delete  do %>
                <i class="fa fa-lg fa-trash"></i></p>
              <% end  %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>        
<% else %>
    <%= render 'parts/static_landing_page' %>
  </div>
<% end %>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-3">
	<h1>New Item</h1>
	<%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-6 col-md-offset-3">
	<%= @item.title %>
	<%= @item.description %><br>


	<%= link_to "<<BACK", root_path %>
	<%= link_to "EDIT", edit_item_path(@item) %>
	<%= link_to "DELETE", item_path(@item), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChecklistDay4346</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'parts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/parts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <%= link_to "Checklist", root_path, class: "navbar-brand" %>
  </div>
  <ul class="nav navbar-nav">
    <% if signed_in? %>
      <%= link_to "New Item", new_item_path, class: 'navbar-text navbar-link'  %>
    <% end %>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if signed_in? %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Log In", new_user_session_path %></li>
    <% end %>
  </ul>
</div>

app/views/parts/_static_landing_page.html.erb
<div class="jumbotron">
  <h1 style="text-align:center;">Welcome to your checklist</h1>
  <h3 style="text-align:center;">Keep track of your stuff</h3>
  <div class="text-center">
    <%= link_to "Sign In to see your list", new_user_session_path, class: 'btn btn-success' %>
  </div>
</div>